version: '3.8'

services:
  app:
    build:
      context: ./edumaster-api
      dockerfile: Dockerfile
    container_name: edumaster-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./edumaster-api:/var/www
      - /var/www/vendor
      - /var/www/storage
    networks:
      - edumaster-network
    depends_on:
      - db
    env_file:
      - ./edumaster-api/.env
    command: >
      sh -c "php artisan migrate --force &&
             php artisan db:seed --force &&
             php artisan cache:clear &&
             php artisan config:clear &&
             php artisan route:clear &&
             php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: edumaster-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edumaster
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - edumaster-network

  nginx:
    image: nginx:alpine
    container_name: edumaster-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - edumaster-network

  frontend:
    build:
      context: ./edumaster-frontend
      dockerfile: Dockerfile
    container_name: edumaster-frontend
    restart: unless-stopped
    ports:
      - '5173:80'
    networks:
      - edumaster-network
    depends_on:
      - app
    environment:
      - VITE_API_URL=http://edumaster-api:8000

volumes:
  db-data:

networks:
  edumaster-network:
    driver: bridge
